[package]
name = "ftooling"
version = "0.1.0"
edition = "2024"

[dependencies]
fprovider = { path = "../fprovider" }

[dev-dependencies]
tokio = { version = "=1.48.0", features = ["macros", "rt-multi-thread"] }
