[package]
name = "fharness"
version = "0.1.0"
edition = "2024"

[dependencies]
fcommon = { path = "../fcommon" }
fchat = { path = "../fchat" }
fmemory = { path = "../fmemory" }
fprovider = { path = "../fprovider" }
ftooling = { path = "../ftooling" }
futures-util = "0.3"

[dev-dependencies]
tokio = { version = "=1.48.0", features = ["macros", "rt-multi-thread"] }

[lib]
doctest = false
