[package]
name = "fprovider"
version = "0.1.0"
edition = "2024"

[features]
default = ["provider-openai"]
provider-opencode-zen = []
provider-openai = [
    "dep:reqwest",
    "dep:serde",
    "dep:serde_json",
    "dep:futures-util",
]
provider-claude = []

[dependencies]
fcommon = { path = "../fcommon" }
futures-core = "0.3"
futures-util = { version = "0.3", optional = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
tokio = { version = "=1.48.0", features = ["macros", "rt-multi-thread"] }

[lib]
doctest = false