[package]
name = "fchat"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3"
fcommon = { path = "../fcommon" }
futures-core = "0.3"
futures-timer = "3"
futures-util = "0.3"
ftooling = { path = "../ftooling" }
fprovider = { path = "../fprovider" }

[dev-dependencies]
tokio = { version = "=1.48.0", features = ["macros", "rt-multi-thread"] }
